services:
  galette:
    image: registry.gitlab.com/smncd/galette/galette
    build: .
    ports:
      - 5000:5000
    environment:
      DEBUG: true
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./:/app
      - ./pages/:/pages
      - ./assets/:/assets