services:
  galette:
    image: registry.gitlab.com/smncd/galette
    build: .
    ports:
      - 5000:5000
    environment:
      DEBUG: true
      RELOAD: true
    volumes:
      - ./:/app
      - ./pages/:/pages
      - ./assets/:/assets